'use client'
import { motion } from 'framer-motion'
import { Scissors, Sparkles, SmilePlus, Plus } from 'lucide-react'
const procedures = [{icon:Scissors,title:'Injerto Capilar',description:'Recupera tu pelo con la técnica FUE o DHI en manos de los mejores especialistas de Estambul.',badge:'Desde 1.800€',badgeColor:'bg-[#C0272D]'},{icon:Sparkles,title:'Cirugía Estética',description:'Aumento de pecho, rinoplastia, liposucción y más. Cirujanos con miles de casos de éxito.',badge:'Desde 2.500€',badgeColor:'bg-[#C0272D]'},{icon:SmilePlus,title:'Estética Dental',description: 'Carilnas, implantes y diseño de sonrisa. Clínicas dentales de primer nivel en Estambul.',badge:'Desde 1.200€',badgeColor:'bg-[#C0272D]'},{icon:Plus,title:'Otras Cirugías',description:'Blefaroplastia, otoplastia, abdominoplastia y más. Consulta tu caso específico con nuestro equipo.',badge:'Consultar',badgeColor:'bg-[#1a1a1a]'}]
const Procedures = () => (
  <section id="procedimientos" className="bg-white py-20 md:py-28 px-4">
    <div className="max-w-6xl mx-auto">
      <motion.div initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin: '-50px'}} transition={{duration:0.6,ease:'easeOut'}} className="text-center mb-16"><h2 className="text-3xl md:text-4xl lg:text-5xl font-black text-[#1a1a1a] mb-4">¿En qué podemos ayudarte?</h2><p className="text-base md:text-lg text-[#666666] max-w-2xl mx-auto">Trabajamos con clínicas especializadas en cada procedimiento. Calidad certificada, precios hasta un <span className="font-semibold text-[#C0272D]">70% más económicos</span> que en España.</p></motion.div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">{procedures.map(({icon:Icon,title,description,badge,badgeColor},i) => (<motion.div key={title} initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-50px'}} transition={{duration:0.5,ease:'easeOut',delay:i*0.1}} className="group border border-gray-100 rounded-xl overflow-hidden hover:shadow-lg transition-shadow duration-300 flex flex-col"><div className="bg-[#F4F4F4] h-44 flex items-center justify-center group-hover:bg-[#1a1a1a] transition-colors duration-300"><Icon size={48} className="text-[#C0272D] group-hover:text-white transition-colors duration-300" /></div><div className="p-6 flex flex-col flex-1"><h3 className="text-lg font-bold text-[#1a1a1a] mb-2">{title}</h3><p className="text-sm text-[#666666] leading-relaxed mb-4 flex-1">{description}</p><div className="mt-auto"><span className={`inline-block px-3 py-1.5 ${badgeColor} text-white text-xs font-bold rounded-full`}>{badge}</span></div></div></motion.div>))}</div>
      <motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-50px'}} transition={{duration:0.5,ease:'easeOut',delay:0.3}} className="text-center mt-12"><a href="#contacto" className="inline-flex items-center justify-center px-8 py-4 bg-[#C0272D] text-white font-semibold rounded-md hover:bg-[#a61f24] transition-colors duration-200">Consulta tu caso gratis</a></motion.div>
    </div>
  </section>
)
export default Procedures
